### ISSUE TITLE
Errors in GCC build

### ISSUE THREAD

**Issue by rosterloh** [mbedmicro/nRF51822#14] opened 2015-06-22 09:32 UTC
Since the recent updates I getting the following errors

```
In file included from C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/BLE.h:47:0,
                 from ../src/main.cpp:9:
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:60:55: error: expected identifier before numeric constant
 #define BLE_UUID_UNKNOWN                              0x0000 /**< Reserved UUID. */
                                                       ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:29:5: note: in expansion of macro 'BLE_UUID_UNKNOWN'
     BLE_UUID_UNKNOWN                             = 0x0000, /**< Reserved UUID. */
     ^
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:60:55: error: expected '}' before numeric constant
 #define BLE_UUID_UNKNOWN                              0x0000 /**< Reserved UUID. */
                                                       ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:29:5: note: in expansion of macro 'BLE_UUID_UNKNOWN'
     BLE_UUID_UNKNOWN                             = 0x0000, /**< Reserved UUID. */
     ^
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:60:55: error: expected unqualified-id before numeric constant
 #define BLE_UUID_UNKNOWN                              0x0000 /**< Reserved UUID. */
                                                       ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:29:5: note: in expansion of macro 'BLE_UUID_UNKNOWN'
     BLE_UUID_UNKNOWN                             = 0x0000, /**< Reserved UUID. */
     ^
In file included from C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/BLE.h:47:0,
                 from ../src/main.cpp:9:
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:95:63: error: expected identifier before numeric constant
 #define BLE_APPEARANCE_UNKNOWN                                0 /**< Unknown. */
                                                               ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:59:5: note: in expansion of macro 'BLE_APPEARANCE_UNKNOWN'
     BLE_APPEARANCE_UNKNOWN                             =    0, /**< Unknown. */
     ^
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:95:63: error: expected '}' before numeric constant
 #define BLE_APPEARANCE_UNKNOWN                                0 /**< Unknown. */
                                                               ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:59:5: note: in expansion of macro 'BLE_APPEARANCE_UNKNOWN'
     BLE_APPEARANCE_UNKNOWN                             =    0, /**< Unknown. */
     ^
C:\Dev\bluetooth-wristband\lib\nRF51822\nordic-sdk\components\softdevice\s130\include/ble_types.h:95:63: error: expected unqualified-id before numeric constant
 #define BLE_APPEARANCE_UNKNOWN                                0 /**< Unknown. */
                                                               ^
C:\Dev\bluetooth-wristband\lib\BLE_API/ble/blecommon.h:59:5: note: in expansion of macro 'BLE_APPEARANCE_UNKNOWN'
     BLE_APPEARANCE_UNKNOWN                             =    0, /**< Unknown. */
```

It seems that the 2 files ble_types.h from nRF51822 and blecommon.h from BLE_API are clashing. ble_types.h have #defines and blecommon.h uses enums

**Comment by rgrover** [comment] 2015-06-30 14:20
duplicate of #16

**Closed by rgrover** 2015-06-30 14:20 UTC
