### ISSUE TITLE
Clash With Definition And Enum Naming

### ISSUE THREAD

**Issue by jcady92** [mbedmicro/nRF51822#16] opened 2015-06-26 20:18 UTC
See: mbedmicro/BLE_API#46

**Comment by jcady92** [comment] 2015-06-28 19:51
I just discovered there's also a file naming clash with the BLE API.  Trying to include "BLE.h" leads to problems because there's also a BLE.h in nrf51822.

**Comment by rgrover** [comment] 2015-06-29 06:45
this is a duplicate of https://github.com/mbedmicro/BLE_API/issues/46
the problem needs to be fixed in nRF51822, not in BLE

**Comment by rgrover** [comment] 2015-06-29 06:49
regarding duplicate BLE.h: the include of BLE.h from BLE_API should be done like:
```
#include "ble/BLE.h"
```

**Comment by jcady92** [comment] 2015-06-29 15:36
I did find one more problem.  There's another naming clash in UARTService.h.

Enum here:

https://github.com/mbedmicro/BLE_API/blob/master/ble/services/UARTService.h#L44

Define here:

https://github.com/mbedmicro/nRF51822/blob/develop/nordic-sdk/components/softdevice/s130/include/ble_gatt.h#L50

Same problem, compiler complains of expected identifier.

**Closed** 2015-07-02 07:51 UTC
Labels: release engineering
